Fix #129: Rename db foreign keys properly
wultra/mobile-utility-server pull request #130
Opened 2023-10-03 10:48 UTC by jandusil

- Review fks

2023-10-03 10:50 UTC, jandusil commented
`mus_mobile_app_fk` was previously wrongly named and at multiple tables causing oracle db to fail

`mus-app-1  | [2023-10-03 09:38:41] SEVERE [liquibase.integration] Migration failed for changeset mobile-utility-server/1.5.x/20230622-add-foreign-keys.xml::2::Lubos Racansky:
mus-app-1  |      Reason: liquibase.exception.DatabaseException: ORA-02264: name already used by an existing constraint
mus-app-1  |  [Failed SQL: (2264) ALTER TABLE POWERAUTH.mus_mobile_domain ADD CONSTRAINT mus_mobile_app_fk FOREIGN KEY (app_id) REFERENCES POWERAUTH.mus_mobile_app (id)]
mus-app-1  | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset mobile-utility-server/1.5.x/20230622-add-foreign-keys.xml::2::Lubos Racansky:
mus-app-1  |      Reason: liquibase.exception.DatabaseException: ORA-02264: name already used by an existing constraint
mus-app-1  |  [Failed SQL: (2264) ALTER TABLE POWERAUTH.mus_mobile_domain ADD CONSTRAINT mus_mobile_app_fk FOREIGN KEY (app_id) REFERENCES POWERAUTH.mus_mobile_app (id)]
mus-app-1  | 	at liquibase.command.CommandScope.execute(CommandScope.java:236)
mus-app-1  | 	at com.datical.liquibase.ext.command.ProUpdateCommandStep.run(Unknown Source)
mus-app-1  | 	at liquibase.command.CommandScope.execute(CommandScope.java:213)
mus-app-1  | 	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
mus-app-1  | 	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
mus-app-1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
mus-app-1  | 	at picocli.CommandLine.access$1500(CommandLine.java:148)
mus-app-1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
mus-app-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
mus-app-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
mus-app-1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
mus-app-1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
mus-app-1  | 	at picocli.CommandLine.execute(CommandLine.java:2170)
mus-app-1  | 	at `

2023-10-05 10:53 UTC, zcgandcomp requested changes

2023-10-05 10:53 UTC, zcgandcomp commented on docs/db/changelog/changesets/mobile-utility-server/1.5.x/20230308-additional-cert-info.xml
> +    <changeSet id="5" author="Jan Dusil" logicalFilePath="mobile-utility-server/1.5.x/20230308-additional-cert-info.xml">
changeset id=4 is OK

changeset id=5 is redundant.
You already have the add of constraint mus_certificate_mobile_domain_id_fk in add-foreign-keys.xml. This is an unnecessary duplicity.

2023-10-09 16:58 UTC, zcgandcomp approved these changes
Looks OK.

2023-10-10 07:38 UTC, merged