Fix #137: Error in after.sql
wultra/mobile-utility-server pull request #140
Opened 2023-10-11 11:43 UTC by banterCZ

Use the original table names from 1.1.0
- mobile_app
- mobile_ssl_pinning

2023-10-11 12:22 UTC, zcgandcomp approved these changes
Looks Ok.

2023-10-11 13:05 UTC, banterCZ commented on docs/sql/postgresql/1.5.0-migration.sql
> +INSERT INTO mus_certificate SELECT * FROM mobile_ssl_pinning;
We have to select columns in a specific order and also insert them into `mus_mobile_domain`. Moreover, we have to fill the `pem` column.

2023-10-12 15:23 UTC, zcgandcomp requested changes

2023-10-12 15:23 UTC, zcgandcomp commented on docs/Mobile-Utility-Server-1.5.0.md
>  3. **Run Liquibase update**:  Execute [liquibase](https://www.liquibase.com/download) scripts located in `docs\db\changelog\db.changelog-master` For convenience, you can use supplied Dockerfiles and
```suggestion
3. **Run Liquibase update**:  Execute [liquibase](https://www.liquibase.com/download) scripts located in `docs\db\changelog\db.changelog-master` 
- For convenience, you can use supplied Dockerfiles and apply the database changes by execute the `docker-db-update.sh` script. 
- If direct update via Liquibase is not possible `liquibase update` command can generate required SQL script.

```

2023-10-12 15:23 UTC, zcgandcomp commented on docs/Mobile-Utility-Server-1.5.0.md
> +6. **Import Certificates**: Certificates are not possible to migrate automatically.
Please add
1) configuration of the administrator (it should be an analogy to the setup of other components filling mus_user and )
2) information "there is a new context path /admin for administrative purposes it should be exposed only in trusted networks.

2023-10-12 15:23 UTC, zcgandcomp commented on docs/Mobile-Utility-Server-1.5.0.md
> +4. **Execute Migration Script**: After applying the Liquibase changes, run the `1.5.0-migration.sql` script
After a discussion with Martin  - we should split this step. Here migrate  mus_mobile_app.
Then after the creation new certificate via API - we can add controls that the new setup is correct i.e. select * from mus_certificate returns values with the same fingerprint as for actual records in the mobile_ssl_pinning.

Then we can recommend dropping old structure.

We can discuss this comment - it's just a precaution.

2023-10-13 05:45 UTC, banterCZ commented on docs/Configuration.md
> +DH4v3SCoDRDUAFBD
The whole section `Creating First Admin User` is analog to documentation in PowerAuth-Cloud, but I afraid that users may tend to use this concrete value instead of their randomly generated ones. cc @romanstrobl

2023-10-13 05:53 UTC, banterCZ commented on docs/Mobile-Utility-Server-1.5.0.md
> +4. **Execute Migration Script**: After applying the Liquibase changes, run the `1.5.0-migration.sql` script
A good idea. It makes sense to split it and make it a little bit safer.

2023-10-13 09:52 UTC, zcgandcomp approved these changes
I'm OK with it.

2023-10-18 07:39 UTC, korbelm approved these changes
LGTM

2023-10-18 07:41 UTC, merged