Fix #144: Executable war
wultra/mobile-utility-server pull request #145
Opened 2023-10-23 08:23 UTC by jnpsk

2023-10-23 08:29 UTC, banterCZ commented on pom.xml
> +                    <artifactId>tomcat-embed-el</artifactId>
Is `tomcat-embed-el` present in `provided-lib`? I am afraid that this excludes the dependency completely. I made the same mistake and tried to fix it in this way. https://github.com/wultra/powerauth-server/pull/1087/files

2023-10-23 08:32 UTC, banterCZ reviewed
Please also double-check the configuration of the `enforcer-plugin`. See https://github.com/wultra/powerauth-server/blob/develop/pom.xml#L223

2023-10-23 08:59 UTC, jnpsk commented on pom.xml
> +                    <artifactId>tomcat-embed-el</artifactId>
I checked the content of the `provided-lib` once more and the it really contains `tomcat-embed-{core,el,websocket}`.

2023-10-23 09:22 UTC, banterCZ commented on pom.xml
> +                    <artifactId>tomcat-embed-el</artifactId>
Yes, you are right, it comes from `spring-boot-starter-tomcat`. So it is up to you, whether to do it via `exclusion` or `dependency-management`, but either way, the enforcer plugin will validate that it is not a part of `WEB-INF/lib`.

2023-10-24 07:31 UTC, banterCZ requested changes
Perfect!
I am requesting changes just to block the merge until **release 1.5.0**

2023-11-01 07:53 UTC, merged