Fix #222: Fix docs versioning and edit database structure docs
wultra/mobile-utility-server pull request #223
Opened 2024-02-22 15:05 UTC by jandusil

2024-02-23 06:46 UTC, banterCZ approved these changes
Looks good to me but let's wait also for review from @zcgandcomp

2024-02-23 08:40 UTC, zcgandcomp requested changes

2024-02-23 08:40 UTC, zcgandcomp commented on docs/Migration-Instructions.md
> +- [Mobile Utility Server 1.4.0](./Mobile-Utility-Server-1.4.0.md)
As we discuss originally. We cannot remove 1.5.0.
we need to have 1.4.0 guideline (as we backport the feature to 1.4.0)
AND 1.5.0 stating that there already can be migration.

2024-02-23 08:46 UTC, jandusil commented on docs/Migration-Instructions.md
> +- [Mobile Utility Server 1.4.0](./Mobile-Utility-Server-1.4.0.md)
@zcgandcomp True, thanks. I have updated the 1.5.0 migration guide as per this comment https://github.com/wultra/mobile-utility-server/pull/174#pullrequestreview-1779184779

2024-02-23 08:48 UTC, zcgandcomp requested changes

2024-02-23 08:48 UTC, zcgandcomp commented on docs/Mobile-Utility-Server-1.5.0.md
> +No migration steps nor database changes are required.
Please mention the backport that shift the original migration to 1.4.x migration. That's the issue. Liquibase, tags, our portal documentation original says migration from 1.1.x to 1.5.0. Ok we shift it so please put this information in the guideline.

2024-02-27 10:08 UTC, zcgandcomp requested changes
Rephrease.

Please backport the guideline so the portal will show the correct version for 1.5.x

2024-02-27 10:08 UTC, zcgandcomp commented on docs/Mobile-Utility-Server-1.5.0.md
> +Please note, version `1.4.x` was introduced as a backport of most functionalities from version `1.5.x`, due to specific
Please note, due to a backport to the version `1.4.x`  database migration to 1.5.x was shifted and described in the guideline TBD link. 
If you are migrating from 1.4.0 there is no other migration needed. If you are migrating from 1.1.x. You need to perform migration steps to 1.4.x first.

2024-02-27 10:29 UTC, jandusil commented on docs/Mobile-Utility-Server-1.5.0.md
> +Please note, version `1.4.x` was introduced as a backport of most functionalities from version `1.5.x`, due to specific
I will prepare backport directly after merge

2024-02-27 10:37 UTC, zcgandcomp approved these changes
Looks OK.

2024-02-27 10:44 UTC, merged