Fix #248: Create standard API Docs for Admin Part
wultra/mobile-utility-server pull request #261
Opened 2024-05-07 10:04 UTC by jandusil

2024-05-07 11:23 UTC, jandusil commented
Converting to draft, found some issues

2024-05-20 09:03 UTC, banterCZ reviewed
I believe that the same change as in `_Sidebar.md_ should be made in `Readme.md` as well.

2024-05-28 19:47 UTC, zcgandcomp requested changes

2024-05-28 19:47 UTC, zcgandcomp commented on docs/Readme.md
> +mobile apps.
Why is the new line here?

2024-05-28 19:47 UTC, zcgandcomp commented on docs/Readme.md
> +at [hello@wultra.com](mailto:hello@wultra.com) for the software use.
Why is the new line here?

2024-05-29 11:47 UTC, zcgandcomp approved these changes
Looks OK

2024-05-29 11:47 UTC, merged