Fix #57: Turn off auto-commit
wultra/mobile-utility-server pull request #58
Opened 2023-03-28 05:16 UTC by banterCZ

See https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/

2023-03-28 12:57 UTC, romanstrobl requested changes
Let's check whether we really need to set both configuration properties.

2023-03-28 12:57 UTC, romanstrobl commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
Can we check whether this configuration is duplicate?

See: https://github.com/spring-projects/spring-boot/commit/22de4303c58663e457caa59ea055a9e95078cdb2

I would prefer to configure just the auto-commit on the datasource, if it is enough. But please check if there are any problems with this, it needs to be tested.

2023-03-29 05:35 UTC, banterCZ commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
Thanks, you are correct. Tested, that `HibernateJpaConfiguration` sets `hibernate.connection.provider_disables_autocommit` based on the value of `spring.datasource.hikari.auto-commit`, see https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.java#L160

2023-03-30 12:26 UTC, petrdvorak approved these changes
Looks OK

2023-03-30 12:34 UTC, merged