Fix #72: Expose endpoint for soft and force update
wultra/mobile-utility-server pull request #73
Opened 2023-06-06 06:32 UTC by banterCZ

```yaml
openapi: 3.0.1
info:
  title: Mobile Utility Server API
  description: Documentation for the Mobile Utility Server RESTful API published by
    the Mobile Utility Server.
  contact:
    name: Wultra s.r.o.
    url: https://www.wultra.com
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: "1.0"
servers:
- url: http://127.0.0.1:8080
  description: Generated server url
paths:
  /app/init/verify-version:
    post:
      tags:
      - App Initialization Controller
      summary: Verify application version.
      description: Verify whether application version is up to date or may be updated
        or should be updated.
      operationId: verifyVersion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyVersionRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VerifyVersionResponse'
  /admin/apps:
    get:
      tags:
      - Administration Controller
      operationId: applicationList
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApplicationListResponse'
    post:
      tags:
      - Administration Controller
      operationId: createApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApplicationDetailResponse'
  /admin/apps/{name}/certificates/pem:
    post:
      tags:
      - Administration Controller
      operationId: createApplicationCertificatePem
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationCertificatePemRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CertificateDetailResponse'
  /admin/apps/{name}/certificates/auto:
    post:
      tags:
      - Administration Controller
      operationId: createApplicationCertificateAuto
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationCertificateRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CertificateDetailResponse'
  /robots.txt:
    get:
      tags:
      - home-controller
      operationId: getRobotsTxt
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /app/init:
    get:
      tags:
      - App Initialization Controller
      operationId: appInit
      parameters:
      - name: appName
        in: query
        required: true
        schema:
          type: string
      - name: X-Cert-Pinning-Challenge
        in: header
        description: Challenge that is included in the response signature. Must be
          at least 16 bytes long.
        required: false
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schem [...]

2023-06-21 13:06 UTC, romanstrobl requested changes
I found several terminology issues.

2023-06-21 14:10 UTC, kober32 commented on src/main/java/com/wultra/app/mobileutilityserver/database/model/MobileAppVersionEntity.java
> +        APPLE
Also voting in favor of `IOS`

2023-06-21 21:42 UTC, petrdvorak commented on src/main/java/com/wultra/app/mobileutilityserver/database/model/MobileAppVersionEntity.java
> +        APPLE
Agreed we currently use `ios` reference in most cases.

> As a side-note, it is fair to say our SDK does not only work on iOS. We do have support for iPadOS, watchOS, and (indirectly) macOS. This is why we use `Apple` reference in some places (i.e., scripts or macros) to refer to all those Apple OS versions.

2023-06-26 12:35 UTC, romanstrobl approved these changes

2023-06-26 22:22 UTC, petrdvorak requested changes
The new endpoint seems unnecessary to me, unless there is a strong reason for the app to call this via a separate endpoint, we can reuse the `GET /app/init` endpoint.

2023-06-26 22:34 UTC, petrdvorak requested changes
Couple more comments...

2023-06-26 22:34 UTC, petrdvorak commented on docs/Database-Structure.md
> +(
We should add `app_id` column so that we can match various configurations intended for a given app.

2023-06-26 22:34 UTC, petrdvorak commented on docs/Public-REST-API.md
> +### Verify Version
Not sure this is required.

2023-06-26 22:34 UTC, petrdvorak commented on src/main/java/com/wultra/app/mobileutilityserver/rest/service/MobileAppService.java
> +        return verifyAndroidVersion(applicationVersion.get(), request);
Why "Android"?

2023-06-27 06:23 UTC, banterCZ commented on src/main/java/com/wultra/app/mobileutilityserver/rest/model/request/VerifyVersionRequest.java
> +public class VerifyVersionRequest {
We have discussed with @kober32 that `user-agent` is a too free structure to rely on. I may try to rewrite it to the query parameters of `GET app/init` to avoid multiple requests.

2023-06-27 06:34 UTC, banterCZ commented on src/main/java/com/wultra/app/mobileutilityserver/rest/service/MobileAppService.java
> +        return verifyAndroidVersion(applicationVersion.get(), request);
🤦 Thanks, left-over after refactoring.

2023-06-27 08:15 UTC, banterCZ commented on docs/Database-Structure.md
> +    application_name  varchar(255) not null,
The question is, whether to keep `application_name` or join `ssl_mobile_app`.

2023-06-28 09:53 UTC, banterCZ commented on src/main/java/com/wultra/app/mobileutilityserver/rest/controller/api/AppInitializationController.java
> +            @RequestParam(value = QueryParams.QUERY_PARAM_APP_VERSION, required = false) String applicationVersion,
Optional parameter because of backward compatibility.

2023-08-22 10:44 UTC, petrdvorak commented on docs/Database-Structure.md
> +    application_name  varchar(255) not null,
I would use a single table for applications. In the next improvement, we can rename `ssl_*` tables to `mus_*`...

2023-08-22 10:46 UTC, petrdvorak commented on docs/Database-Structure.md
> +    application_name  varchar(255) not null,
(Meaning I would join to an existing table.)

2023-08-22 10:50 UTC, petrdvorak approved these changes
Looks OK

2023-08-22 12:31 UTC, banterCZ commented on docs/Database-Structure.md
> +    application_name  varchar(255) not null,
The application name is not duplicated anymore but joined.

2023-08-22 12:38 UTC, merged