Fix #87: Rename tables to be less connected with SSL topic
wultra/mobile-utility-server pull request #97
Opened 2023-08-30 23:43 UTC by jandusil

- Rename tables from ssl* prefix to mus*

2023-09-04 06:03 UTC, banterCZ commented on docs/db/changelog/changesets/mobile-utility-server/1.5.x/20230227-initial-import.xml
> +                <sequenceExists sequenceName="mus_mobile_app_seq"/>
I am afraid that these changes have already been deployed to customers and should be implemented as incremental changes. @petrdvorak @zcgandcomp Am I correct?

2023-09-05 11:00 UTC, zcgandcomp commented on docs/db/changelog/changesets/mobile-utility-server/1.5.x/20230227-initial-import.xml
> +                <sequenceExists sequenceName="mus_mobile_app_seq"/>
Yes, and no. I believe we are fine from liquibase POV. BUT we need to do migration.

for me the sequence is as follows:
1) prepare migration scripts - I assume pure SQL for migration guide - part of the issue #87.
2) prepare the LB in new naming - from scratch installation will be fine and migration will be taken care of by the migration script.

i.e. whoever will want to update to 1.5.0 and has a previous installation has to run the migration script
and the rest is taken care of the liquibase.

We do not need to solve the cases when the liquibase itself is already executed somewhere as it's only testing of the snapshot.

2023-09-18 08:55 UTC, zcgandcomp requested changes
update the proper attributes for sequences in LB.
Add migration script.

2023-09-18 08:55 UTC, zcgandcomp commented on docs/db/changelog/changesets/mobile-utility-server/1.5.x/20230227-initial-import.xml
> +        <createSequence sequenceName="mus_mobile_app_seq" maxValue="9999999999999" cacheSize="20"/>
no maxValues please.
startValue and incrementBy is required.

2023-09-26 12:42 UTC, zcgandcomp approved these changes
Looks OK

2023-09-26 12:46 UTC, merged